<?php

namespace App\Http\Controllers;

use App\Services\Places\GooglePlaces;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Address lookup for the site fields, in two steps.
 *
 * The browser asks this rather than Google directly, so the API key stays on
 * the server: there is no key in the page source, nothing to restrict by
 * referrer, and nothing to leak.
 *
 * Two endpoints because the flow has two halves. Typing asks for names;
 * picking one asks for the place behind it. A session token supplied by the
 * caller ties them together, so a whole search plus its one details call bill
 * as a single session.
 *
 * Both are throttled, and both answer with an empty result rather than an
 * error when the lookup cannot be done — the field is an ordinary text box
 * when this returns nothing.
 */
class AddressLookupController extends Controller
{
    /** Addresses matching what has been typed so far. */
    public function suggest(Request $request, GooglePlaces $places): JsonResponse
    {
        $data = $request->validate([
            'q' => ['required', 'string', 'max:160'],
            // Opaque to us: generated by the field, passed to Google, thrown
            // away after a selection.
            'session' => ['required', 'string', 'max:64'],
        ]);

        return response()->json([
            'suggestions' => array_map(
                fn ($suggestion) => $suggestion->toArray(),
                $places->suggest($data['q'], $data['session']),
            ),
        ]);
    }

    /**
     * The place behind a suggestion — asked once, when someone picks one.
     *
     * `place` is null when Google could not resolve it, which the field reads
     * as "keep what was typed, without a point" rather than as a failure.
     */
    public function place(Request $request, GooglePlaces $places): JsonResponse
    {
        $data = $request->validate([
            'place_id' => ['required', 'string', 'max:512'],
            'session' => ['required', 'string', 'max:64'],
        ]);

        $place = $places->details($data['place_id'], $data['session']);

        return response()->json(['place' => $place?->toArray()]);
    }
}
